image: thorstenwagner/docker-java8-maven
#image: kaiwinter/docker-java8-maven
#maven:3-jdk-7

before_script:
  - "export JAVA_HOME=/usr/lib/jvm/jre-1.8.0-openjdk"
  - "yum install which -y"
  - "Xvfb :99 &"
  - "export DISPLAY=:99"

maven_build:
  stage: build
  script:
  - "mvn clean package"
  - "cat target/site/jacoco/index.html"