image: kaiwinter/docker-java8-maven
#maven:3-jdk-7

before_script:
  - "yum install Xvfb firefox"

maven_build:
  stage: build
  script:
  - "Xvfb :99 &"
  - "export DISPLAY=:99"
  - "mvn clean package"
  - "cat target/site/jacoco/index.html"